In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.linear_model import Perceptron

In [2]:
df = pd.read_csv("amazon_musical_instruments_reviews.csv")

In [6]:
df=pd.DataFrame(df)

In [7]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,column_name
0,A2IBPI20UZIR0U,1384719342,"cassandra tu ""Yeah, well, that's just like, u...","[0, 0]","Not much to write about here, but it does exac...",5.0,good,1393545600,"02 28, 2014",Positive
1,A14VAT5EAX3D9S,1384719342,Jake,"[13, 14]",The product does exactly as it should and is q...,5.0,Jake,1363392000,"03 16, 2013",Positive
2,A195EZSQDW3E21,1384719342,"Rick Bennette ""Rick Bennette""","[1, 1]",The primary job of this device is to block the...,5.0,It Does The Job Well,1377648000,"08 28, 2013",Positive
3,A2C00NNG1ZQQG2,1384719342,"RustyBill ""Sunday Rocker""","[0, 0]",Nice windscreen protects my MXL mic and preven...,5.0,GOOD WINDSCREEN FOR THE MONEY,1392336000,"02 14, 2014",Positive
4,A94QU4C90B1AX,1384719342,SEAN MASLANKA,"[0, 0]",This pop filter is great. It looks and perform...,5.0,No more pops when I record my vocals.,1392940800,"02 21, 2014",Positive

In [8]:
df=df.dropna(subset=['reviewerName'])
df=df.dropna(subset=['reviewText'])

In [9]:
def f(row):
   
    if row['overall'] == 3.0:
        val = 'Neutral'

    elif row['overall'] == 1.0 or row['overall'] == 2.0:
        val = 'Negative'

    elif row['overall'] == 4.0 or row['overall'] == 5.0:
        val = 'Positive'

    else:
        val = -1

    return val

df['reviews'] = df.apply(f, axis=1)
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,column_name,reviews
0,A2IBPI20UZIR0U,1384719342,"cassandra tu ""Yeah, well, that's just like, u...","[0, 0]","Not much to write about here, but it does exac...",5.0,good,1393545600,"02 28, 2014",Positive,Positive
1,A14VAT5EAX3D9S,1384719342,Jake,"[13, 14]",The product does exactly as it should and is q...,5.0,Jake,1363392000,"03 16, 2013",Positive,Positive
2,A195EZSQDW3E21,1384719342,"Rick Bennette ""Rick Bennette""","[1, 1]",The primary job of this device is to block the...,5.0,It Does The Job Well,1377648000,"08 28, 2013",Positive,Positive
3,A2C00NNG1ZQQG2,1384719342,"RustyBill ""Sunday Rocker""","[0, 0]",Nice windscreen protects my MXL mic and preven...,5.0,GOOD WINDSCREEN FOR THE MONEY,1392336000,"02 14, 2014",Positive,Positive
4,A94QU4C90B1AX,1384719342,SEAN MASLANKA,"[0, 0]",This pop filter is great. It looks and perform...,5.0,No more pops when I record my vocals.,1392940800,"02 21, 2014",Positive,Positive

In [10]:
df['reviews']=df['summary']+' '+df['reviewText']

In [11]:
x=df['reviewText']
y=df['overall']


vectorizer=CountVectorizer()
x=vectorizer.fit_transform(x)

joblib.dump(vectorizer,"new_amazon_musical_instruments_reviews.pkl")

['new_amazon_musical_instruments_reviews.pkl']

In [12]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()
x,y=smote.fit_resample(x,y)

In [13]:
y.value_counts()

overall
5.0    6912
3.0    6912
4.0    6912
2.0    6912
1.0    6912
Name: count, dtype: int64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [16]:
model=MLPClassifier(hidden_layer_sizes=(100,),solver="lbfgs")
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print(y_pred)   
joblib.dump(model,"new_model_amazon_musical_instruments_reviews.pkl")

[2. 2. 3. ... 1. 4. 5.]

d:\TechAxis\venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

['new_model_amazon_musical_instruments_reviews.pkl']

In [ ]:

print(confusion_matrix(y_test,y_pred))

#Detailed classification report 
print("\nClassification Report: ")
print(classification_report(y_test,y_pred))